로그인 기능 구현
kakao-tech-campus-2nd-step3/Team12_BE pull request #15
Opened 2024-10-04 12:58 UTC by yoonsu0325

- 카카오 로그인 구현

현재 build.gradle 때문에 충돌이 일어나는 것 같습니다...

2024-10-08 05:09 UTC, HSHwan commented
고생 많으셨습니다! 궁금한 점이 있어 코멘트 남겼는데 확인 부탁드립니다!

2024-10-08 06:12 UTC, yoonsu0325 commented
> 고생 많으셨습니다! 궁금한 점이 있어 코멘트 남겼는데 확인 부탁드립니다!

넵 뭐가 궁금하신가요

2024-10-08 06:25 UTC, HSHwan commented
리뷰 내용 확인해주시고 답변해주시면 감사하겠습니다!

2024-10-08 06:39 UTC, HSHwan requested changes
해당 리뷰 확인해주시고 답변 부탁드립니다!

2024-10-08 06:39 UTC, HSHwan commented on src/main/java/katecam/luvicookie/ditto/domain/user/domain/User.java
> +    private String socialId;
카카오 로그인만 하는데 해당 필드는 어떻게 쓰이는지 궁금합니다!

2024-10-08 06:39 UTC, HSHwan commented on src/main/java/katecam/luvicookie/ditto/domain/login/oauth/LoginSuccessHandler.java
> +        if (member.getRole().equals(Role.GUEST)) {
해당 코드는 아래 코드처럼 User 도메인 내에서 Guest 판별을 하는 게 어떨까요?
```java
public boolean isGuest() {
  return role.equals(Role.GUEST);
}
```

2024-10-08 07:35 UTC, yoonsu0325 commented on src/main/java/katecam/luvicookie/ditto/domain/user/domain/User.java
> +        this.role = Role.USER;
회원가입이 완료된 경우 role이 GUEST에서 USER로 바뀌는 거라서 메서드명을 authorizeUser로 했습니다.

2024-10-08 07:52 UTC, HSHwan commented on src/main/java/katecam/luvicookie/ditto/domain/user/domain/User.java
> +        this.role = Role.USER;
이해했습니다! 설명해주셔서 감사합니다

2024-10-08 07:57 UTC, yoonsu0325 commented on src/main/java/katecam/luvicookie/ditto/domain/user/domain/User.java
> +    private String socialId;
위에 적혀있는대로 사용자 구분하는 용도입니다. 카카오 로그인의 경우에는 이메일을 받아올 수 없기 때문에 socialId라는 값으로 사용자를 구분합니다.

2024-10-11 05:48 UTC, HSHwan approved these changes

2024-10-11 05:49 UTC, merged