로그인 최종
kakao-tech-campus-2nd-step3/Team12_BE pull request #56
Opened 2024-11-12 11:20 UTC by yoonsu0325

2024-11-12 14:57 UTC, HSHwan requested changes
고생하셨습니다! 리뷰 확인하시고 수정 부탁드립니다

2024-11-12 14:57 UTC, HSHwan commented on src/main/java/katecam/luvicookie/ditto/domain/member/dto/response/MemberResponse.java
> +        @JsonProperty("id")
profile_image로 수정하셔야 할 것 같습니다

2024-11-13 00:15 UTC, yoonsu0325 commented on src/main/java/katecam/luvicookie/ditto/domain/member/dto/response/MemberResponse.java
> +        @JsonProperty("id")
수정했습니다

2024-11-13 01:35 UTC, HSHwan approved these changes

2024-11-13 01:35 UTC, merged